name: Java CI

on: [push]

jobs:
  build-and-deploy-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Checkstyle
      run: mvn checkstyle:checkstyle
    - name: Run SpotBugs
      run: mvn com.github.spotbugs:spotbugs-maven-plugin:check
    - name: Install Doxygen and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - name: Generate LaTeX documentation with Doxygen
      run: doxygen Doxyfile
    - name: Compile LaTeX documentation to PDF
      run: |
        cd ./latex
        pdflatex refman.tex
        pdflatex refman.tex
    - name: Upload PDF to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: documentation-pdf
        path: ./latex/refman.pdf
    - name: Run unit tests
      run: mvn test
